### ISSUE TITLE
analysis: User ダッシュボードのためのデータ保存Batch処理

### ISSUE THREAD

**Issue by Apollo716** [senspace-studio/card#126]
## 【Background】
UserからStack獲得の方法やルールについての問い合わせが多数ある。
docsとしてルールブックは出しているものの、自分の数字や他のプレイヤーの数字を見て個々人が戦略を立てられるようにしたい。
また、数字など目に見える形で出すことによって、ゲーム自体の透明化を図りたい。

## 【WANT】
Playerが各々Cardに関するデータをチャートなどで確認できるようなダッシュボードを作りたい。 ref) https://farcasteruserstats.com/
それにあたって、データ集計周りのデータ（json）設計とバッチ処理を実装したい。（ダッシュボード自体の実装は別Issueで出します）

具体的には、**Battle Data**, **Invite Data**, **Individual Stack Data**, **Reward Data**の4つのデータを毎日バッチ処理でS3に保存したい。
それぞれのjsonの中身は以下、

### Battle Data　(日付ごとに別ファイル)

3 AM UTCを基準に過去23:59:59 の実績を参照

```
[
  {
    "gameId": "GAME123456",
    "maker": "0x1234567890123456789012345678901234567890",
    "challenger": "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    "winner": "0x1234567890123456789012345678901234567890",
    "loser": "0xabcdefabcdefabcdefabcdefabcdefabcdefabcd",
    "isDraw": false,
    "createdBlockNumber": 12345,
    "createdAt": "2024-07-03T15:30:00Z"
  }
]
```

### InvitationTransfer Data (日付ごとに別ファイル)

3 AM UTCを基準に過去23:59:59 の実績を参照

```
[
  {
    "inviter": "0x9876543210987654321098765432109876543210",
    "invitee": "0xfedcba9876543210fedcba9876543210fedcba98",
    "tokenId": 1234,
    "createdBlockNumber": 12345,
    "createdAt": "2024-07-03T18:45:30.123Z"
  }
]
```

### Individual Stack Data (日付ごとに別ファイル)

3 AM UTCを基準に過去23:59:59 の実績を参照

```
[
  "date": "2024/07/03",
  "algorithm": "HC-01",
  "data": [{
    "address": "0x3a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b",
    "score": 1000
  }]
]
```

`https://i3w8pqcmtm.ap-northeast-1.awsapprunner.com/points/calcurate-score?end_date_unix=1720148400000` のようにend_date_unixにミリ秒で渡すとその時刻を基準にスコア計算が回るエンドポイントがあるのでそれを使用。Returnまでに毎回計算しなおすので10秒ほどかかる。
algorithmは環境変数でセットする

### Reward History Data (一つのファイル)

3 AM UTCを基準に過去23:59:59 の実績を参照

```
[
  {
    "maxRewardAmount": 100000,
    "difficulty": 0.008,
    "bonusMultiplier": 2,
    "totalStack": 10000000,
    "date": "2024/07/03"
  }
]
```

- MaxRewardAmountは プレー数 x 190 になる。（GameRevealedイベントでプレー数は参照できる）
- difficultyは[このコントラクト](https://explorer.degen.tips/address/0xED6580AC5A2bD603c872b28D361983428d90caA9?tab=read_contract)の `difficultyTop / difficultyBottom` で計算できる。
- bonusMultiplierは上記同コントラクトの`bonusMultiprierTop / bonusMultiprierBottom` で計算できる。
- totalStackはIndividualStackの当日の合計

## 【TODO】

- [x] thirdwebのengineから上記4つのjsonをS3に保存。（UTC 00:00:00~23:59:59 まで）
- [x] file名はそれぞれ、`battle/yyyymmdd.json`,` invite/yyyymmdd.json`, `individualStack/yyyymmdd.json`, `reward/history.json` ex) `battle/20240703.json`
- [ ] batch処理のエラー(engine叩けないとか、rpc node叩けないとか)でjsonファイル作成できない際は [#error-tracking](https://discord.com/channels/920207624945942528/1223797574385799279)にwebhook飛ばす（簡易的なエラーメッセージで良いかと）
